FA.JustBlog/Controllers/CategoriesController.cs
using FA.JustBlog.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FA.JustBlog.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            var allCategory = CategoryBusiness.GetAllCategory();
            // trả về view hiển thị ra toàn bộ danh sách của category
            return View();
        }

        public ActionResult GetCategoryForMenu()
        {
            var allCategoryMenu = CategoryBusiness.GetAllCategory();
            // trả về view hiển thị ra toàn bộ danh sách của category
            return PartialView("_PartialMenuCategory", allCategoryMenu.ToList());
        }
    }
}

FA.JustBlog/Controllers/PostsController.cs
using FA.JustBlog.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FA.JustBlog.Controllers
{
    public class PostsController : Controller
    {
        // GET: Post
        public ActionResult Index()
        {
            var allPost = PostBusiness.GetAllPost();
            // trả về view hiển thị ra toàn bộ danh sách của post
            return View(allPost);
        }
       
        public ActionResult Detail(int id)
        {
            var post = PostBusiness.GetDetail(id);
            PostBusiness.Update(id);
            return View(post);     
        }

        [ChildActionOnly]
        public ActionResult LastestPosts()
        {
            var allLastestPost = PostBusiness.GetLastestPost(5);
            return PartialView("_ListPost", allLastestPost.ToList());
        }

        [ChildActionOnly]
        public ActionResult MostViewedPosts()
        {
            var allLastestPost = PostBusiness.GetMostViewPost(5);
            return PartialView("_ListPost", allLastestPost.ToList());
        }
        
        public ActionResult GetPostByCategory(string id)
        {
            var allPostByCategory = PostBusiness.GetPostByCategory(id);
            return View("Index", allPostByCategory);
        }

        public ActionResult GetPostByDateAndTitle(int year, int month, string urlSlug)
        {
            
            var post = PostBusiness.GetPostByDateAndTitle(year, month, urlSlug);
            if (post == null)
                return HttpNotFound();
            int id = post.PostId;
            PostBusiness.Update(id);
            return View("Detail", post);
        }

        public ActionResult GetPostByTag(string tagName)
        {
            var listPost = PostBusiness.GetPostByTag(tagName);
            return View("Index", listPost);
        }
    }
}

FA.JustBlog/Controllers/TagController.cs
using FA.JustBlog.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FA.JustBlog.Controllers
{
    public class TagController : Controller
    {
        // GET: Tag
        public ActionResult GetAllTag()
        {
            var getAllTag = TagBusiness.GetAllTag();

            return PartialView("_PartialTag", getAllTag.ToList());
        }
    }
}

FA.JustBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="icon" type="image/x-icon" href="~/Asset/assets/favicon.ico"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Asset/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            @Html.ActionLink("JustBlog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                    @Html.Action("GetCategoryForMenu","Categories", new { area = "" })
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->

    <header class="masthead" style="background-image: url('/Asset/assets/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <span class="subheading">A Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content-->
    <div class="container row">
        <div class="col-lg-9 mx-auto">
            @RenderBody()

        </div>
        <div class="col-lg-3 mx-auto">
            @Html.Action("AboutCard", "Home")
            <h3>Mostviewed Post</h3>
            @Html.Action("MostViewedPosts", "Home")
            <h3>Lastest Post</h3>
            @Html.Action("LastestPost", "Home")
            <h3>Popular Tags</h3>
            @Html.Action("GetAllTag", "Tag")
        </div>
    </div>
    <!-- Footer-->
    @Html.Partial("_PartialFooter")
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Asset/js/scripts.js"></script>
</body>
</html>

FA.JustBlog/Views/Shared/_PartialFooter.cshtml
<footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                </div>
            </div>
        </div>
    </footer>

FA.JustBlog/Views/Shared/_PartialMenuCategory.cshtml
@model IEnumerable<FA.JustBlog.ViewModels.CategoryViewModel>

@if (Model != null && Model.Count() > 0)
{
    foreach (var category in Model)
    {
       
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="@Url.Action("GetPostByCategory","Posts", new { id = category.Name})">@category.Name</a></li>
    }
}